# Generated by Django 5.1.3 on 2025-01-03 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=50)),
                ('upload_platform', models.CharField(max_length=100)),
                ('upload_status', models.CharField(default='pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Media',
            },
        ),
    ]
